[selene]
base = "lua51"

[vim.call]
any = true

[[vim.call.args]]
type = "string"

[[vim.call.args]]
type = "..."
required = false

[[vim.fn."*".args]]
type = "..."
required = false

# Vim-specific globals:

[[vim.command.args]]
type = "string"

[[vim.dict.args]]
type = "table"

[[vim.eval.args]]
type = "string"

# Neovim-specific globals:

[vim.NIL]
property = true

[[vim.api.nvim_eval.args]]
type = "string"

[[vim.cmd.args]]
type = "string"

[[vim.deep_equal.args]]
type = "any"

[[vim.deep_equal.args]]
type = "any"

[[vim.deepcopy.args]]
type = "any"

[[vim.gsplit.args]]
type = "string"

[[vim.gsplit.args]]
type = "string"

[[vim.gsplit.args]]
type = "bool"

[[vim.inspect.args]]
type = "any"

[[vim.lsp.start_client.args]]
type = "table"

[[vim.tbl_keys.args]]
type = "table"

[vim.type_idx]
property = true

[vim.types.dictionary]
property = true

[[vim.validate.args]]
type = "table"
