name: CI

on: [push, pull_request]

jobs:
  stylua:
    name: Check format with StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: '^0.12'

  selene:
    name: Lint with selene
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install selene
        run: |
          VERSION='0.16.0'
          SHA256='a02e93ecba434e10a2731cab0a1d6cb6c26454545fc4174626f9d38ae6000b8b'
          curl -fLOSs "https://github.com/Kampfkarren/selene/releases/download/$VERSION/selene-$VERSION-linux.zip"
          sha256sum --check --strict <<< "$SHA256 selene-$VERSION-linux.zip"
          unzip "selene-$VERSION-linux.zip"
          install -c -m 755 selene /usr/local/bin/selene
      - run: selene lua
      - name: selene test
        run: selene .
        working-directory: test

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        vim:
          - nvim
          - vim
        version:
          - stable
        include:
          - os: ubuntu-latest
            vim: nvim
            version: nightly
    continue-on-error: ${{ matrix.version == 'nightly' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: ${{ matrix.vim == 'nvim' }}
          version: ${{ matrix.version }}
      - name: Checkout vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - run: make test-${{ matrix.vim }}
